# 1
  true
# 2
  g++ -c foo.c
# 3
  : : :
# 4
  if
      cat</etc/passwd \
    |
      tr a-z A-Z \
    |
      sort -u
  then
    :
  else
    echo sort failed!
  fi
# 5
  a b<c>d
# 6
  if
      cat</etc/passwd \
    |
      tr a-z A-Z \
    |
      sort -u>out
  then
    :
  else
    echo sort failed!
  fi
# 7
  if
    if
        a \
      ;
        a \
      ;
        a
    then
      b
    else
      :
    fi
  then
    if
      c
    then
      if
          d \
        |
          e
      then
        f
      fi
    fi
  fi
# 8
  g<h
# 9
  while
    while
        until
          :
        do
          echo yoo hoo!
        done \
      ;
        false
    do
      (
         a \
       |
         b
      )
    done>f
  do
    :>g
  done
# 10
    a<b>c \
  |
    d<e>f \
  |
    g<h>i
